import * as dns from 'dns';
// Ensure reliable DNS resolution for MongoDB Atlas SRV records
try {
  dns.setServers(['8.8.8.8', '1.1.1.1']);
} catch {
  // Ignore if not permitted
}

import * as mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import * as path from 'path';

// Load .env
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const uri = process.env.MONGODB_URI ;
if (!uri) {
  throw new Error('❌ MONGODB_URI is not defined in .env');
}


async function seed() {
  console.log('⚡ Connecting to MongoDB:', uri.replace(/:[^:@]+@/, ':****@'));
  await mongoose.connect(uri);
  console.log('✅ Connected successfully.');

  const db = mongoose.connection.db!;

  console.log('\n--- 1. Seeding 9 Booran Dealership Precincts (Rooftops) ---');
  const rooftops = [
    {
      rooftopId: 'ROOFTOP-DANDENONG',
      name: 'Booran Dandenong',
      code: 'DAN',
      address: '147 Lathams Road',
      suburb: 'Carrum Downs',
      state: 'VIC',
      postcode: '3201',
      phone: '+61 3 9793 9999',
      pentanaSiteCode: 'DAN01',
      oemBrandCodes: ['TOYOTA', 'LEXUS', 'HYUNDAI'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-BERWICK',
      name: 'Booran Berwick',
      code: 'BER',
      address: '1–5 Clyde Road',
      suburb: 'Berwick',
      state: 'VIC',
      postcode: '3806',
      phone: '+61 3 8768 2222',
      pentanaSiteCode: 'BER01',
      oemBrandCodes: ['NISSAN', 'SUZUKI', 'KIA'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-CHELTENHAM',
      name: 'Booran Cheltenham',
      code: 'CHE',
      address: '1235 Nepean Highway',
      suburb: 'Cheltenham',
      state: 'VIC',
      postcode: '3192',
      phone: '+61 3 9584 4066',
      pentanaSiteCode: 'CHE01',
      oemBrandCodes: ['VOLKSWAGEN', 'SKODA'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-CRANBOURNE',
      name: 'Booran Cranbourne',
      code: 'CRA',
      address: '206 S Gippsland Highway',
      suburb: 'Cranbourne',
      state: 'VIC',
      postcode: '3977',
      phone: '+61 3 5991 2300',
      pentanaSiteCode: 'CRA01',
      oemBrandCodes: ['MITSUBISHI', 'HOLDEN'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-MORNINGTON',
      name: 'Booran Mornington',
      code: 'MOR',
      address: '93 Mornington-Tyabb Road',
      suburb: 'Mornington',
      state: 'VIC',
      postcode: '3931',
      phone: '+61 3 5975 1111',
      pentanaSiteCode: 'MOR01',
      oemBrandCodes: ['MAZDA', 'SUBARU'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-FRANKSTON',
      name: 'Booran Frankston',
      code: 'FRA',
      address: '83 Wells Road',
      suburb: 'Frankston',
      state: 'VIC',
      postcode: '3199',
      phone: '+61 3 9783 3322',
      pentanaSiteCode: 'FRA01',
      oemBrandCodes: ['FORD', 'ISUZU'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-FERNTREE-GULLY',
      name: 'Booran Ferntree Gully',
      code: 'FTG',
      address: '980 Burwood Highway',
      suburb: 'Ferntree Gully',
      state: 'VIC',
      postcode: '3156',
      phone: '+61 3 9758 8888',
      pentanaSiteCode: 'FTG01',
      oemBrandCodes: ['TOYOTA', 'GWM'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-PAKENHAM',
      name: 'Booran Pakenham',
      code: 'PAK',
      address: '25 Southeast Boulevard',
      suburb: 'Pakenham',
      state: 'VIC',
      postcode: '3810',
      phone: '+61 3 5941 7777',
      pentanaSiteCode: 'PAK01',
      oemBrandCodes: ['HYUNDAI', 'KIA'],
      isActive: true,
      timezone: '+10:00',
    },
    {
      rooftopId: 'ROOFTOP-WARRAGUL',
      name: 'Booran Warragul',
      code: 'WAR',
      address: '150 Queen Street',
      suburb: 'Warragul',
      state: 'VIC',
      postcode: '3820',
      phone: '+61 3 5622 3444',
      pentanaSiteCode: 'WAR01',
      oemBrandCodes: ['MITSUBISHI', 'NISSAN'],
      isActive: true,
      timezone: '+10:00',
    },
  ];

  for (const rt of rooftops) {
    await db.collection('rooftops').updateOne(
      { rooftopId: rt.rooftopId },
      { $set: { ...rt, updatedAt: new Date() }, $setOnInsert: { createdAt: new Date() } },
      { upsert: true }
    );
  }
  console.log(`✅ Upserted ${rooftops.length} Booran rooftops.`);

  console.log('\n--- 2. Seeding Rooftop Franchises & Feed Health ---');
  await db.collection('franchises').deleteMany({});
  await db.collection('feedhealths').deleteMany({});

  const franchiseList: any[] = [];
  const feedHealthList: any[] = [];

  for (const rt of rooftops) {
    // Pentana DMS feed health
    feedHealthList.push({
      rooftopId: rt.rooftopId,
      feedType: 'pentana',
      brandCode: null,
      status: 'ok',
      lastSyncAt: new Date(Date.now() - 4 * 60 * 1000),
      lastCheckedAt: new Date(),
      message: 'Pentana Connect v12.4 online. Latency optimal.',
      latencyMs: 38 + Math.floor(Math.random() * 25),
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    for (const brand of rt.oemBrandCodes) {
      franchiseList.push({
        rooftopId: rt.rooftopId,
        brandCode: brand,
        brandName: `${brand.charAt(0) + brand.slice(1).toLowerCase()} Genuine Parts`,
        oemFeedEndpoint: `https://oem-gateway.booran.com.au/api/${brand.toLowerCase()}`,
        pentanaFranchiseCode: `${rt.code}_${brand.substring(0, 3)}`,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      feedHealthList.push({
        rooftopId: rt.rooftopId,
        feedType: 'oem',
        brandCode: brand,
        status: 'ok',
        lastSyncAt: new Date(Date.now() - 8 * 60 * 1000),
        lastCheckedAt: new Date(),
        message: `${brand} EPC electronic catalogue feed synchronized.`,
        latencyMs: 55 + Math.floor(Math.random() * 30),
        createdAt: new Date(),
        updatedAt: new Date(),
      });
    }
  }

  await db.collection('franchises').insertMany(franchiseList);
  await db.collection('feedhealths').insertMany(feedHealthList);
  console.log(`✅ Inserted ${franchiseList.length} franchises & ${feedHealthList.length} feed-health monitors.`);

  console.log('\n--- 3. Seeding Trade Accounts (Matching Registered User IDs) ---');
  const accounts = [
    {
      accountId: 'ACC-000123',
      companyName: 'Dandenong Smash Repairs Pty Ltd',
      contactName: 'David Vance',
      contactEmail: 'david.vance@dandenongsmash.com.au',
      contactPhone: '+61 3 9791 4455',
      paymentTerms: 'NET30',
      creditLimitCents: 5000000, // $50,000.00
      currentBalanceCents: 1245000, // $12,450.00
      discountPercent: 17.5,
      creditHold: false,
      isOverdue: false,
      isActive: true,
      ytdSpendCents: 4892000, // $48,920.00
      ytdOrderCount: 42,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-DANDENONG',
      lastSyncedAt: new Date(),
    },
    {
      accountId: 'ACC-001',
      companyName: 'Melbourne Prestige Autobody',
      contactName: 'Ayla Imran',
      contactEmail: 'imranayla73@gmail.com',
      contactPhone: '+61 3 9544 8822',
      paymentTerms: 'NET30',
      creditLimitCents: 8000000, // $80,000.00
      currentBalanceCents: 2130000, // $21,300.00
      discountPercent: 20.0,
      creditHold: false,
      isOverdue: false,
      isActive: true,
      ytdSpendCents: 9450000, // $94,500.00
      ytdOrderCount: 78,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-DANDENONG',
      lastSyncedAt: new Date(),
    },
    {
      accountId: 'ACC-002',
      companyName: 'Bayside Mechanical & Fleet Services',
      contactName: 'Robert Smith',
      contactEmail: 'service@baysidemechanical.com.au',
      contactPhone: '+61 3 9583 1200',
      paymentTerms: 'NET14',
      creditLimitCents: 3500000, // $35,000.00
      currentBalanceCents: 480000, // $4,800.00
      discountPercent: 15.0,
      creditHold: false,
      isOverdue: false,
      isActive: true,
      ytdSpendCents: 2840000,
      ytdOrderCount: 26,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-CHELTENHAM',
      lastSyncedAt: new Date(),
    },
    {
      accountId: 'ACC-003',
      companyName: 'Frankston Crash Experts',
      contactName: 'Mark Taylor',
      contactEmail: 'mark@frankstoncrash.com.au',
      contactPhone: '+61 3 9781 9911',
      paymentTerms: 'COD',
      creditLimitCents: 2500000, // $25,000.00
      currentBalanceCents: 2680000, // $26,800.00 (Over limit)
      discountPercent: 12.0,
      creditHold: true, // ON CREDIT HOLD
      isOverdue: true,
      isActive: true,
      ytdSpendCents: 3120000,
      ytdOrderCount: 19,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-FRANKSTON',
      lastSyncedAt: new Date(),
    },
    {
      accountId: 'ACC-004',
      companyName: 'Peninsula European Specialists',
      contactName: 'Stefan Weber',
      contactEmail: 'workshop@peninsulaeuro.com.au',
      contactPhone: '+61 3 5975 6677',
      paymentTerms: 'NET30',
      creditLimitCents: 6500000, // $65,000.00
      currentBalanceCents: 840000, // $8,400.00
      discountPercent: 18.5,
      creditHold: false,
      isOverdue: false,
      isActive: true,
      ytdSpendCents: 5410000,
      ytdOrderCount: 38,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-MORNINGTON',
      lastSyncedAt: new Date(),
    },
    {
      accountId: 'ACC-005',
      companyName: 'South East Commercial Fleet Repairs',
      contactName: 'Gary Bennett',
      contactEmail: 'gary@southeastfleet.com.au',
      contactPhone: '+61 3 9706 7788',
      paymentTerms: 'EOM',
      creditLimitCents: 12000000, // $120,000.00
      currentBalanceCents: 3850000, // $38,500.00
      discountPercent: 22.0,
      creditHold: false,
      isOverdue: false,
      isActive: true,
      ytdSpendCents: 14200000,
      ytdOrderCount: 114,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-DANDENONG',
      lastSyncedAt: new Date(),
    },
    {
      accountId: '12345',
      companyName: 'Cranbourne Precision Auto Repairs',
      contactName: 'Hammad Ali',
      contactEmail: 'hammadak05@gmail.com',
      contactPhone: '+61 3 5996 4433',
      paymentTerms: 'NET30',
      creditLimitCents: 4000000, // $40,000.00
      currentBalanceCents: 720000, // $7,200.00
      discountPercent: 15.0,
      creditHold: false,
      isOverdue: false,
      isActive: true,
      ytdSpendCents: 3670000,
      ytdOrderCount: 29,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-CRANBOURNE',
      lastSyncedAt: new Date(),
    },
    {
      accountId: 'acc-000',
      companyName: 'Good Showroom Internal Trade Counter',
      contactName: 'Counter Supervisor',
      contactEmail: 'admin@goodshowroom.com',
      contactPhone: '+61 3 9793 0000',
      paymentTerms: 'NET30',
      creditLimitCents: 10000000, // $100,000.00
      currentBalanceCents: 0,
      discountPercent: 25.0,
      creditHold: false,
      isOverdue: false,
      isActive: true,
      ytdSpendCents: 6500000,
      ytdOrderCount: 52,
      ytdYear: 2026,
      rooftopId: 'ROOFTOP-DANDENONG',
      lastSyncedAt: new Date(),
    },
  ];

  for (const acc of accounts) {
    await db.collection('tradeaccounts').updateOne(
      { accountId: acc.accountId },
      { $set: { ...acc, updatedAt: new Date() }, $setOnInsert: { createdAt: new Date() } },
      { upsert: true }
    );
  }
  console.log(`✅ Upserted ${accounts.length} trade accounts.`);

  console.log('\n--- 4. Seeding Fast-Moving OEM Parts Catalogue ---');
  const parts = [
    // TOYOTA
    {
      partNumber: '04465-0D060',
      partNumberNormalised: '044650D060',
      brandCode: 'TOYOTA',
      description: 'Front Disc Brake Pad Set Genuine',
      descriptionLong: 'Toyota Genuine Ceramic Front Disc Brake Pad Set with shims and grease.',
      groupCode: 'BRAKE',
      groupName: 'Brakes & Hydraulics',
      keywords: ['brake', 'pad', 'pads', 'disc', 'ceramic', 'front', 'corolla', 'yaris'],
      vehicleFitment: ['COROLLA', 'YARIS', 'PRIUS'],
      vehicleRange: 'Toyota Corolla 2018–2023 (ZRE172R / MZEA12R)',
      listPriceCents: 14850, // $148.50
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'SET',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '04152-YZZA6',
      partNumberNormalised: '04152YZZA6',
      brandCode: 'TOYOTA',
      description: 'Engine Oil Filter Element with O-Ring',
      descriptionLong: 'Toyota Genuine cartridge-type engine oil filter with drain tube and Viton O-ring.',
      groupCode: 'FILTER',
      groupName: 'Filtration & Fluids',
      keywords: ['oil', 'filter', 'cartridge', 'element', 'service', 'corolla', 'rav4', 'camry'],
      vehicleFitment: ['COROLLA', 'RAV4', 'CAMRY', 'KLUGER'],
      vehicleRange: 'Toyota RAV4 / Camry / Corolla 2.5L Hybrid & Petrol',
      listPriceCents: 2450, // $24.50
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '17801-21050',
      partNumberNormalised: '1780121050',
      brandCode: 'TOYOTA',
      description: 'Engine Air Cleaner Filter Element',
      descriptionLong: 'Toyota Genuine high-flow pleated engine air intake filter.',
      groupCode: 'FILTER',
      groupName: 'Filtration & Fluids',
      keywords: ['air', 'filter', 'cleaner', 'intake', 'service', 'yaris', 'corolla'],
      vehicleFitment: ['COROLLA', 'YARIS'],
      vehicleRange: 'Toyota Corolla / Yaris 1.5L & 1.8L',
      listPriceCents: 4200, // $42.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '43512-02250',
      partNumberNormalised: '4351202250',
      brandCode: 'TOYOTA',
      description: 'Front Brake Disc Rotor Ventilated',
      descriptionLong: 'Toyota Genuine vented front brake rotor 275mm.',
      groupCode: 'BRAKE',
      groupName: 'Brakes & Hydraulics',
      keywords: ['rotor', 'disc', 'brake', 'front', 'vented', 'corolla'],
      vehicleFitment: ['COROLLA', 'PRIUS'],
      vehicleRange: 'Toyota Corolla 2013–2022',
      listPriceCents: 18500, // $185.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '52119-02980',
      partNumberNormalised: '5211902980',
      brandCode: 'TOYOTA',
      description: 'Front Bumper Cover Primer Coated',
      descriptionLong: 'Toyota Genuine front bumper bar fascia for smash repair, primed ready for painting.',
      groupCode: 'BODY',
      groupName: 'Smash & Body Panels',
      keywords: ['bumper', 'bar', 'fascia', 'front', 'smash', 'panel', 'corolla'],
      vehicleFitment: ['COROLLA'],
      vehicleRange: 'Toyota Corolla Hatchback 2019–2024',
      listPriceCents: 52000, // $520.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '81110-02E60',
      partNumberNormalised: '8111002E60',
      brandCode: 'TOYOTA',
      description: 'Right Hand LED Headlamp Assembly',
      descriptionLong: 'Toyota Genuine RH LED headlight unit with integrated DRL.',
      groupCode: 'LIGHTING',
      groupName: 'Lighting & Electrical',
      keywords: ['headlight', 'headlamp', 'led', 'lamp', 'rh', 'right', 'corolla'],
      vehicleFitment: ['COROLLA'],
      vehicleRange: 'Toyota Corolla Sedan / Hatch 2020+',
      listPriceCents: 98000, // $980.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },

    // NISSAN
    {
      partNumber: 'D1060-1KA1A',
      partNumberNormalised: 'D10601KA1A',
      brandCode: 'NISSAN',
      description: 'Front Brake Pad Set Genuine Nissan',
      descriptionLong: 'Nissan Genuine front brake pads for X-Trail and Qashqai.',
      groupCode: 'BRAKE',
      groupName: 'Brakes & Hydraulics',
      keywords: ['brake', 'pad', 'pads', 'nissan', 'xtrail', 'qashqai'],
      vehicleFitment: ['XTRAIL', 'QASHQAI', 'JUKE'],
      vehicleRange: 'Nissan X-Trail T32 / Qashqai J11 2014–2021',
      listPriceCents: 15600, // $156.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'SET',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '15208-65F0E',
      partNumberNormalised: '1520865F0E',
      brandCode: 'NISSAN',
      description: 'Spin-On Engine Oil Filter',
      descriptionLong: 'Nissan Genuine spin-on filter with anti-drainback valve.',
      groupCode: 'FILTER',
      groupName: 'Filtration & Fluids',
      keywords: ['oil', 'filter', 'spinon', 'navara', 'xtrail', 'patrol'],
      vehicleFitment: ['NAVARA', 'XTRAIL', 'PATROL'],
      vehicleRange: 'Nissan Navara D23 / X-Trail / Patrol',
      listPriceCents: 2200, // $22.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '21410-1KA0A',
      partNumberNormalised: '214101KA0A',
      brandCode: 'NISSAN',
      description: 'Engine Cooling Radiator Assembly',
      descriptionLong: 'Nissan Genuine aluminium core radiator assembly.',
      groupCode: 'COOLING',
      groupName: 'Cooling & Heating',
      keywords: ['radiator', 'cooling', 'coolant', 'xtrail'],
      vehicleFitment: ['XTRAIL'],
      vehicleRange: 'Nissan X-Trail T32 2.5L 2014–2022',
      listPriceCents: 44000, // $440.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },

    // HYUNDAI
    {
      partNumber: '58101-2VA50',
      partNumberNormalised: '581012VA50',
      brandCode: 'HYUNDAI',
      description: 'Front Disc Brake Pad Kit',
      descriptionLong: 'Hyundai Genuine Front brake pads with wear indicators.',
      groupCode: 'BRAKE',
      groupName: 'Brakes & Hydraulics',
      keywords: ['brake', 'pad', 'pads', 'hyundai', 'i30', 'tucson', 'kona'],
      vehicleFitment: ['I30', 'TUCSON', 'KONA'],
      vehicleRange: 'Hyundai i30 PD / Tucson TL 2016–2023',
      listPriceCents: 13900, // $139.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'SET',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '26300-35505',
      partNumberNormalised: '2630035505',
      brandCode: 'HYUNDAI',
      description: 'Spin-On Oil Filter with Washer',
      descriptionLong: 'Hyundai & Kia OEM spin-on heavy duty oil filter.',
      groupCode: 'FILTER',
      groupName: 'Filtration & Fluids',
      keywords: ['oil', 'filter', 'hyundai', 'i30', 'tucson', 'santafe'],
      vehicleFitment: ['I30', 'TUCSON', 'SANTAFE', 'KONA'],
      vehicleRange: 'Hyundai / Kia 1.6L, 2.0L & 2.4L engines',
      listPriceCents: 1950, // $19.50
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },

    // MITSUBISHI
    {
      partNumber: '4605A265',
      partNumberNormalised: '4605A265',
      brandCode: 'MITSUBISHI',
      description: 'Front Disc Brake Pad Set Heavy Duty',
      descriptionLong: 'Mitsubishi Genuine Triton and Pajero Sport brake pad kit.',
      groupCode: 'BRAKE',
      groupName: 'Brakes & Hydraulics',
      keywords: ['brake', 'pads', 'triton', 'pajero', 'mitsubishi'],
      vehicleFitment: ['TRITON', 'PAJERO'],
      vehicleRange: 'Mitsubishi Triton MQ / MR 2015–2023',
      listPriceCents: 16500, // $165.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'SET',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '1770A053',
      partNumberNormalised: '1770A053',
      brandCode: 'MITSUBISHI',
      description: 'Diesel Fuel Filter Element with Water Sensor Port',
      descriptionLong: 'Mitsubishi Genuine common rail diesel fuel filter.',
      groupCode: 'FILTER',
      groupName: 'Filtration & Fluids',
      keywords: ['fuel', 'filter', 'diesel', 'triton', 'pajero'],
      vehicleFitment: ['TRITON', 'PAJERO'],
      vehicleRange: 'Mitsubishi Triton 2.4L 4N15 Diesel',
      listPriceCents: 6800, // $68.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },

    // FORD
    {
      partNumber: 'BRF-1445',
      partNumberNormalised: 'BRF1445',
      brandCode: 'FORD',
      description: 'Front Brake Disc Rotor Pair Genuine Ford',
      descriptionLong: 'Ford Ranger PX front ventilated rotor pair.',
      groupCode: 'BRAKE',
      groupName: 'Brakes & Hydraulics',
      keywords: ['rotor', 'brake', 'disc', 'ranger', 'everest', 'ford'],
      vehicleFitment: ['RANGER', 'EVEREST'],
      vehicleRange: 'Ford Ranger PX1 / PX2 / PX3 3.2L & 2.0L Bi-Turbo',
      listPriceCents: 24500, // $245.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'PAIR',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: 'FL-910S',
      partNumberNormalised: 'FL910S',
      brandCode: 'FORD',
      description: 'Motorcraft Engine Oil Filter',
      descriptionLong: 'Ford Motorcraft premium filter with silicone anti-drainback.',
      groupCode: 'FILTER',
      groupName: 'Filtration & Fluids',
      keywords: ['oil', 'filter', 'motorcraft', 'ranger', 'focus', 'ford'],
      vehicleFitment: ['RANGER', 'FOCUS', 'ESCAPE'],
      vehicleRange: 'Ford Ranger / Focus / Escape EcoBoost',
      listPriceCents: 2100, // $21.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },

    // VOLKSWAGEN
    {
      partNumber: '5Q0698151B',
      partNumberNormalised: '5Q0698151B',
      brandCode: 'VOLKSWAGEN',
      description: 'Front Brake Pad Set MQB Platform',
      descriptionLong: 'Volkswagen Genuine low-dust ceramic formulation brake pads.',
      groupCode: 'BRAKE',
      groupName: 'Brakes & Hydraulics',
      keywords: ['brake', 'pad', 'pads', 'golf', 'tiguan', 'passat', 'vw'],
      vehicleFitment: ['GOLF', 'TIGUAN', 'PASSAT'],
      vehicleRange: 'Volkswagen Golf 7 / 8 / Tiguan MQB platform',
      listPriceCents: 17800, // $178.00
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'SET',
      lastSyncedAt: new Date(),
    },
    {
      partNumber: '06L115562B',
      partNumberNormalised: '06L115562B',
      brandCode: 'VOLKSWAGEN',
      description: 'Engine Oil Filter Cartridge EA888',
      descriptionLong: 'Volkswagen Genuine oil filter cartridge with crush washer and O-rings.',
      groupCode: 'FILTER',
      groupName: 'Filtration & Fluids',
      keywords: ['oil', 'filter', 'ea888', 'golf', 'gti', 'tiguan'],
      vehicleFitment: ['GOLF', 'TIGUAN', 'PASSAT'],
      vehicleRange: 'Volkswagen 2.0 TSI EA888 Gen 3',
      listPriceCents: 2850, // $28.50
      coreChargeCents: 0,
      isActive: true,
      isSuperseded: false,
      supersededByPartNumber: null,
      unitOfMeasure: 'EACH',
      lastSyncedAt: new Date(),
    },
  ];

  for (const p of parts) {
    await db.collection('parts').updateOne(
      { partNumber: p.partNumber, brandCode: p.brandCode },
      { $set: { ...p, updatedAt: new Date() }, $setOnInsert: { createdAt: new Date() } },
      { upsert: true }
    );
  }
  console.log(`✅ Upserted ${parts.length} fast-moving catalogue parts across Toyota, Nissan, Hyundai, Mitsubishi, Ford & VW.`);

  console.log('\n--- 5. Seeding Realistic Orders across Operational States ---');
  await db.collection('orders').deleteMany({});

  const now = Date.now();
  const sampleOrders = [
    {
      orderNumber: 'ORD-20260925-A101',
      tradeAccountId: 'ACC-000123',
      rooftopId: 'ROOFTOP-DANDENONG',
      placedByUserId: 'usr-david-vance-001',
      placedByEmail: 'david.vance@dandenongsmash.com.au',
      placedByName: 'David Vance',
      state: 'SUBMITTED',
      subtotalCents: 245000,
      coreChargeTotalCents: 0,
      gstCents: 20213,
      totalCents: 222338, // $2,223.38
      totalLines: 2,
      pickedLinesCount: 0,
      deliveryMethod: 'COLLECTION',
      customerReference: 'PO-88912 Vance Smash',
      hasExceptions: false,
      statusHistory: [],
      lines: [
        {
          lineId: 'LIN-01',
          partNumber: '04465-0D060',
          partNumberNormalised: '044650D060',
          brandCode: 'TOYOTA',
          description: 'Front Disc Brake Pad Set Genuine',
          quantity: 4,
          unitPriceCents: 12251,
          coreChargeCents: 0,
          totalPriceCents: 49004,
          state: 'ALLOCATED',
          sourceKind: 'BRANCH',
          sourceName: 'Booran Dandenong Main Store',
          sourceRooftopId: 'ROOFTOP-DANDENONG',
          binLocation: 'A-04',
          eta: 'Available for immediate dispatch',
          pickedQuantity: 0,
          pickedAt: null,
          pickedBy: null,
          exception: null,
          reSourceHistory: [],
        },
        {
          lineId: 'LIN-02',
          partNumber: '52119-02980',
          partNumberNormalised: '5211902980',
          brandCode: 'TOYOTA',
          description: 'Front Bumper Cover Primer Coated',
          quantity: 2,
          unitPriceCents: 42900,
          coreChargeCents: 0,
          totalPriceCents: 85800,
          state: 'ALLOCATED',
          sourceKind: 'BRANCH',
          sourceName: 'Booran Dandenong Main Store',
          sourceRooftopId: 'ROOFTOP-DANDENONG',
          binLocation: 'BULK-12',
          eta: 'Available for immediate dispatch',
          pickedQuantity: 0,
          pickedAt: null,
          pickedBy: null,
          exception: null,
          reSourceHistory: [],
        },
      ],
      createdAt: new Date(now - 30 * 60 * 1000), // 30m ago
      updatedAt: new Date(now - 30 * 60 * 1000),
    },
    {
      orderNumber: 'ORD-20260925-B202',
      tradeAccountId: 'ACC-001',
      rooftopId: 'ROOFTOP-DANDENONG',
      placedByUserId: 'usr-ayla-imran-002',
      placedByEmail: 'imranayla73@gmail.com',
      placedByName: 'Ayla Imran',
      state: 'PROCESSING',
      subtotalCents: 382000,
      coreChargeTotalCents: 0,
      gstCents: 30560,
      totalCents: 336160, // $3,361.60
      totalLines: 2,
      pickedLinesCount: 1,
      deliveryMethod: 'DELIVERY',
      customerReference: 'Ayla Autobody Job #552',
      hasExceptions: false,
      statusHistory: [
        {
          fromState: 'SUBMITTED',
          toState: 'PROCESSING',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 1.5 * 3600 * 1000),
          notes: null,
        },
      ],
      lines: [
        {
          lineId: 'LIN-01',
          partNumber: '81110-02E60',
          partNumberNormalised: '8111002E60',
          brandCode: 'TOYOTA',
          description: 'Right Hand LED Headlamp Assembly',
          quantity: 2,
          unitPriceCents: 78400,
          coreChargeCents: 0,
          totalPriceCents: 156800,
          state: 'ALLOCATED',
          sourceKind: 'BRANCH',
          sourceName: 'Booran Dandenong Main Store',
          sourceRooftopId: 'ROOFTOP-DANDENONG',
          binLocation: 'B-02',
          eta: 'In progress',
          pickedQuantity: 0,
          pickedAt: null,
          pickedBy: null,
          exception: null,
          reSourceHistory: [],
        },
        {
          lineId: 'LIN-02',
          partNumber: '43512-02250',
          partNumberNormalised: '4351202250',
          brandCode: 'TOYOTA',
          description: 'Front Brake Disc Rotor Ventilated',
          quantity: 4,
          unitPriceCents: 14800,
          coreChargeCents: 0,
          totalPriceCents: 59200,
          state: 'PICKED',
          sourceKind: 'BRANCH',
          sourceName: 'Booran Dandenong Main Store',
          sourceRooftopId: 'ROOFTOP-DANDENONG',
          binLocation: 'C-08',
          pickedQuantity: 4,
          pickedAt: new Date(now - 15 * 60 * 1000),
          pickedBy: 'counter.controller@booran.com.au',
          exception: null,
          reSourceHistory: [],
        },
      ],
      createdAt: new Date(now - 2 * 3600 * 1000),
      updatedAt: new Date(now - 15 * 60 * 1000),
    },
    {
      orderNumber: 'ORD-20260925-C303',
      tradeAccountId: 'ACC-002',
      rooftopId: 'ROOFTOP-CHELTENHAM',
      placedByUserId: 'usr-robert-smith-003',
      placedByEmail: 'service@baysidemechanical.com.au',
      placedByName: 'Robert Smith',
      state: 'PICKED',
      subtotalCents: 185000,
      coreChargeTotalCents: 0,
      gstCents: 15725,
      totalCents: 172975, // $1,729.75
      totalLines: 1,
      pickedLinesCount: 1,
      deliveryMethod: 'COLLECTION',
      customerReference: 'Bayside Servicing Run #1',
      hasExceptions: false,
      statusHistory: [
        {
          fromState: 'SUBMITTED',
          toState: 'PROCESSING',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 3 * 3600 * 1000),
          notes: null,
        },
        {
          fromState: 'PROCESSING',
          toState: 'PICKED',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 45 * 60 * 1000),
          notes: null,
        },
      ],
      lines: [
        {
          lineId: 'LIN-01',
          partNumber: '5Q0698151B',
          partNumberNormalised: '5Q0698151B',
          brandCode: 'VOLKSWAGEN',
          description: 'Front Brake Pad Set MQB Platform',
          quantity: 6,
          unitPriceCents: 15130,
          coreChargeCents: 0,
          totalPriceCents: 90780,
          state: 'PICKED',
          sourceKind: 'BRANCH',
          sourceName: 'Booran Cheltenham Parts',
          sourceRooftopId: 'ROOFTOP-CHELTENHAM',
          binLocation: 'V-04',
          pickedQuantity: 6,
          pickedAt: new Date(now - 45 * 60 * 1000),
          pickedBy: 'counter.controller@booran.com.au',
          exception: null,
          reSourceHistory: [],
        },
      ],
      createdAt: new Date(now - 4 * 3600 * 1000),
      updatedAt: new Date(now - 45 * 60 * 1000),
    },
    {
      orderNumber: 'ORD-20260924-D404',
      tradeAccountId: 'ACC-004',
      rooftopId: 'ROOFTOP-MORNINGTON',
      placedByUserId: 'usr-stefan-weber-004',
      placedByEmail: 'workshop@peninsulaeuro.com.au',
      placedByName: 'Stefan Weber',
      state: 'DISPATCHED',
      subtotalCents: 520000,
      coreChargeTotalCents: 0,
      gstCents: 42380,
      totalCents: 466180, // $4,661.80
      totalLines: 1,
      pickedLinesCount: 1,
      deliveryMethod: 'COURIER',
      customerReference: 'Peninsula Fleet Service 441',
      hasExceptions: false,
      statusHistory: [
        {
          fromState: 'SUBMITTED',
          toState: 'PROCESSING',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 20 * 3600 * 1000),
          notes: null,
        },
        {
          fromState: 'PROCESSING',
          toState: 'PICKED',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 6 * 3600 * 1000),
          notes: null,
        },
        {
          fromState: 'PICKED',
          toState: 'DISPATCHED',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 2 * 3600 * 1000),
          notes: null,
        },
      ],
      lines: [
        {
          lineId: 'LIN-01',
          partNumber: '06L115562B',
          partNumberNormalised: '06L115562B',
          brandCode: 'VOLKSWAGEN',
          description: 'Engine Oil Filter Cartridge EA888',
          quantity: 20,
          unitPriceCents: 2323,
          coreChargeCents: 0,
          totalPriceCents: 46460,
          state: 'PICKED',
          sourceKind: 'BRANCH',
          sourceName: 'Booran Mornington Store',
          sourceRooftopId: 'ROOFTOP-MORNINGTON',
          binLocation: null,
          pickedQuantity: 20,
          pickedAt: new Date(now - 6 * 3600 * 1000),
          pickedBy: 'counter.controller@booran.com.au',
          exception: null,
          reSourceHistory: [],
        },
      ],
      createdAt: new Date(now - 24 * 3600 * 1000),
      updatedAt: new Date(now - 2 * 3600 * 1000),
    },
    {
      orderNumber: 'ORD-20260925-E505',
      tradeAccountId: 'ACC-000123',
      rooftopId: 'ROOFTOP-DANDENONG',
      placedByUserId: 'usr-david-vance-001',
      placedByEmail: 'david.vance@dandenongsmash.com.au',
      placedByName: 'David Vance',
      state: 'EXCEPTION',
      subtotalCents: 198000,
      coreChargeTotalCents: 0,
      gstCents: 16335,
      totalCents: 179685, // $1,796.85
      totalLines: 1,
      pickedLinesCount: 0,
      deliveryMethod: 'DELIVERY',
      customerReference: 'Dandenong Smash Insurance Claim #9001',
      hasExceptions: true,
      statusHistory: [
        {
          fromState: 'SUBMITTED',
          toState: 'EXCEPTION',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 55 * 60 * 1000),
          notes: 'Out of stock — re-source required',
        },
      ],
      lines: [
        {
          lineId: 'LIN-01',
          partNumber: '21410-1KA0A',
          partNumberNormalised: '214101KA0A',
          brandCode: 'NISSAN',
          description: 'Engine Cooling Radiator Assembly',
          quantity: 1,
          unitPriceCents: 36300,
          coreChargeCents: 0,
          totalPriceCents: 36300,
          state: 'EXCEPTION',
          sourceKind: 'SISTER',
          sourceName: 'Booran Berwick (Sister Branch)',
          sourceRooftopId: 'ROOFTOP-BERWICK',
          binLocation: 'RAD-01',
          eta: 'Inter-branch transfer required (ETA +3 hrs)',
          pickedQuantity: 0,
          pickedAt: null,
          pickedBy: null,
          exception: {
            reason: 'OUT_OF_STOCK',
            description: 'Primary branch stock depleted. Re-routing to Berwick sister branch.',
            raisedAt: new Date(now - 55 * 60 * 1000),
            raisedBy: 'counter.controller@booran.com.au',
            resolvedAt: null,
            resolvedBy: null,
            resolutionNotes: null,
          },
          reSourceHistory: [],
        },
      ],
      createdAt: new Date(now - 1 * 3600 * 1000),
      updatedAt: new Date(now - 1 * 3600 * 1000),
    },
    {
      orderNumber: 'ORD-20260923-F606',
      tradeAccountId: 'ACC-005',
      rooftopId: 'ROOFTOP-DANDENONG',
      placedByUserId: 'usr-gary-bennett-005',
      placedByEmail: 'gary@southeastfleet.com.au',
      placedByName: 'Gary Bennett',
      state: 'DELIVERED',
      subtotalCents: 640000,
      coreChargeTotalCents: 0,
      gstCents: 49920,
      totalCents: 549120, // $5,491.20
      totalLines: 1,
      pickedLinesCount: 1,
      deliveryMethod: 'DELIVERY',
      customerReference: 'SE Commercial Weekly Delivery',
      hasExceptions: false,
      statusHistory: [
        {
          fromState: 'SUBMITTED',
          toState: 'PROCESSING',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 40 * 3600 * 1000),
          notes: null,
        },
        {
          fromState: 'PROCESSING',
          toState: 'PICKED',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 24 * 3600 * 1000),
          notes: null,
        },
        {
          fromState: 'PICKED',
          toState: 'DISPATCHED',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 18 * 3600 * 1000),
          notes: null,
        },
        {
          fromState: 'DISPATCHED',
          toState: 'DELIVERED',
          changedBy: 'counter.controller@booran.com.au',
          changedAt: new Date(now - 12 * 3600 * 1000),
          notes: null,
        },
      ],
      lines: [
        {
          lineId: 'LIN-01',
          partNumber: 'BRF-1445',
          partNumberNormalised: 'BRF1445',
          brandCode: 'FORD',
          description: 'Front Brake Disc Rotor Pair Genuine Ford',
          quantity: 8,
          unitPriceCents: 19110,
          coreChargeCents: 0,
          totalPriceCents: 152880,
          state: 'PICKED',
          sourceKind: 'BRANCH',
          sourceName: 'Booran Frankston Store',
          sourceRooftopId: 'ROOFTOP-FRANKSTON',
          binLocation: null,
          pickedQuantity: 8,
          pickedAt: new Date(now - 24 * 3600 * 1000),
          pickedBy: 'counter.controller@booran.com.au',
          exception: null,
          reSourceHistory: [],
        },
      ],
      createdAt: new Date(now - 48 * 3600 * 1000),
      updatedAt: new Date(now - 12 * 3600 * 1000),
    },
  ];

  await db.collection('orders').insertMany(sampleOrders);
  console.log(`✅ Inserted ${sampleOrders.length} realistic orders across states (SUBMITTED, PROCESSING, PICKED, DISPATCHED, EXCEPTION, DELIVERED).`);

  console.log('\n--- 6. Seeding PartsCheck RFQ Inbound Inbox & SLA Clock Data ---');
  await db.collection('partscheckrfqs').deleteMany({});

  const sampleRfqs = [
    {
      rfqId: 'PC-RFQ-10293',
      buyerId: 'BUYER-REP-DAN-01',
      repairerName: 'Dandenong Smash Repairs Pty Ltd',
      repairerEmail: 'david.vance@dandenongsmash.com.au',
      repairerPhone: '+61 3 9791 4455',
      tradeAccountId: 'ACC-000123',
      isBuyerMapped: true,
      rooftopId: 'ROOFTOP-DANDENONG',
      claimNumber: 'CLM-VIC-98442',
      repairOrderNumber: 'RO-DAN-4412',
      vehicleDetails: {
        make: 'TOYOTA',
        model: 'Corolla Hatch',
        year: 2021,
        vin: 'JTN11566810239102',
        rego: '1XY9AB',
      },
      deadline: new Date(now + 42 * 60 * 1000), // 42 mins remaining
      status: 'RECEIVED',
      subtotalCents: 133551,
      coreChargeTotalCents: 0,
      gstCents: 13355,
      totalCents: 146906,
      lines: [
        {
          lineId: 'PC-LIN-01',
          partNumber: '04465-0D060',
          partNumberNormalised: '044650D060',
          description: 'Front Brake Pad Set Genuine',
          quantity: 1,
          status: 'RESOLVED',
          resolvedPriceCents: 12251,
          unitTradePriceCents: 12251,
          coreChargeCents: 0,
          totalPriceCents: 12251,
          stockQty: 8,
          binLocation: 'A-04',
          inStock: true,
          resolvedSourceKind: 'BRANCH',
          resolvedSourceName: 'Booran Dandenong Main Store',
          resolvedSourceRooftopId: 'ROOFTOP-DANDENONG',
        },
        {
          lineId: 'PC-LIN-02',
          partNumber: '52119-02980',
          partNumberNormalised: '5211902980',
          description: 'Front Bumper Cover Primer Coated',
          quantity: 1,
          status: 'RESOLVED',
          resolvedPriceCents: 42900,
          unitTradePriceCents: 42900,
          coreChargeCents: 0,
          totalPriceCents: 42900,
          stockQty: 2,
          binLocation: 'BULK-12',
          inStock: true,
          resolvedSourceKind: 'BRANCH',
          resolvedSourceName: 'Booran Dandenong Main Store',
          resolvedSourceRooftopId: 'ROOFTOP-DANDENONG',
        },
        {
          lineId: 'PC-LIN-03',
          partNumber: '81110-02E60',
          partNumberNormalised: '8111002E60',
          description: 'Right Hand LED Headlamp Unit',
          quantity: 1,
          status: 'RESOLVED',
          resolvedPriceCents: 78400,
          unitTradePriceCents: 78400,
          coreChargeCents: 0,
          totalPriceCents: 78400,
          stockQty: 1,
          binLocation: 'B-02',
          inStock: true,
          resolvedSourceKind: 'BRANCH',
          resolvedSourceName: 'Booran Dandenong Main Store',
          resolvedSourceRooftopId: 'ROOFTOP-DANDENONG',
        },
      ],
      createdAt: new Date(now - 18 * 60 * 1000),
      updatedAt: new Date(now - 18 * 60 * 1000),
    },
    {
      rfqId: 'PC-RFQ-10294',
      buyerId: 'BUYER-REP-MPA-09',
      repairerName: 'Melbourne Prestige Autobody',
      repairerEmail: 'imranayla73@gmail.com',
      repairerPhone: '+61 3 9544 8822',
      tradeAccountId: 'ACC-001',
      isBuyerMapped: true,
      rooftopId: 'ROOFTOP-DANDENONG',
      claimNumber: 'CLM-SUNCORP-771',
      repairOrderNumber: 'RO-MPA-9811',
      vehicleDetails: {
        make: 'TOYOTA',
        model: 'RAV4 Hybrid',
        year: 2022,
        vin: 'JTMBZ11V20D009182',
        rego: '1ZZ3CD',
      },
      deadline: new Date(now + 120 * 60 * 1000),
      status: 'AUTO_QUOTED',
      quotedAt: new Date(now - 12 * 60 * 1000),
      quotedBy: 'SYSTEM_AUTO',
      subtotalCents: 33520,
      coreChargeTotalCents: 0,
      gstCents: 3352,
      totalCents: 36872,
      lines: [
        {
          lineId: 'PC-LIN-01',
          partNumber: '04152-YZZA6',
          partNumberNormalised: '04152YZZA6',
          description: 'Engine Oil Filter Cartridge',
          quantity: 2,
          status: 'RESOLVED',
          resolvedPriceCents: 1960,
          unitTradePriceCents: 1960,
          coreChargeCents: 0,
          totalPriceCents: 3920,
          stockQty: 24,
          inStock: true,
          resolvedSourceKind: 'BRANCH',
          resolvedSourceName: 'Booran Dandenong Main Store',
          resolvedSourceRooftopId: 'ROOFTOP-DANDENONG',
        },
        {
          lineId: 'PC-LIN-02',
          partNumber: '43512-02250',
          partNumberNormalised: '4351202250',
          description: 'Front Brake Disc Rotor',
          quantity: 2,
          status: 'RESOLVED',
          resolvedPriceCents: 14800,
          unitTradePriceCents: 14800,
          coreChargeCents: 0,
          totalPriceCents: 29600,
          stockQty: 6,
          inStock: true,
          resolvedSourceKind: 'BRANCH',
          resolvedSourceName: 'Booran Dandenong Main Store',
          resolvedSourceRooftopId: 'ROOFTOP-DANDENONG',
        },
      ],
      createdAt: new Date(now - 25 * 60 * 1000),
      updatedAt: new Date(now - 12 * 60 * 1000),
    },
    {
      rfqId: 'PC-RFQ-10295',
      buyerId: 'BUYER-UNKNOWN-99',
      repairerName: 'Oakleigh Independent Bodyworks',
      repairerEmail: 'orders@oakleighbody.com.au',
      tradeAccountId: null,
      isBuyerMapped: false,
      rooftopId: 'ROOFTOP-DANDENONG',
      claimNumber: 'CLM-RACV-4412',
      vehicleDetails: {
        make: 'VOLKSWAGEN',
        model: 'Golf TSI',
        year: 2020,
        vin: 'WVWZZZAUZLP019284',
        rego: '1AA2BB',
      },
      deadline: new Date(now + 15 * 60 * 1000), // 15 mins remaining
      status: 'UNMAPPED_BUYER',
      subtotalCents: 0,
      coreChargeTotalCents: 0,
      gstCents: 0,
      totalCents: 0,
      lines: [
        {
          lineId: 'PC-LIN-01',
          partNumber: '5Q0698151B',
          partNumberNormalised: '5Q0698151B',
          description: 'Front Brake Pad Set MQB Platform',
          quantity: 1,
          status: 'PENDING',
          resolvedPriceCents: null,
          unitTradePriceCents: null,
          coreChargeCents: 0,
          totalPriceCents: null,
          stockQty: 0,
          inStock: false,
          resolvedSourceKind: null,
          resolvedSourceName: null,
          resolvedSourceRooftopId: null,
        },
      ],
      createdAt: new Date(now - 45 * 60 * 1000),
      updatedAt: new Date(now - 45 * 60 * 1000),
    },
  ];

  await db.collection('partscheckrfqs').insertMany(sampleRfqs);
  console.log(`✅ Inserted ${sampleRfqs.length} PartsCheck RFQ simulations (RECEIVED, AUTO_QUOTED, UNMAPPED_BUYER).`);

  console.log('\n--- 7. Seeding Activity Logs (Audit Events) ---');
  const sampleAuditEvents = [
    {
      action: 'LOGIN',
      userId: 'david.vance@dandenongsmash.com.au',
      tradeAccountId: 'ACC-000123',
      rooftopId: 'ROOFTOP-DANDENONG',
      metadata: { method: 'EMAIL_PASSWORD', client: 'Next.js Web PWA' },
      createdAt: new Date(now - 35 * 60 * 1000),
    },
    {
      action: 'ORDER_SUBMIT',
      userId: 'david.vance@dandenongsmash.com.au',
      orderNumber: 'ORD-20260925-A101',
      tradeAccountId: 'ACC-000123',
      rooftopId: 'ROOFTOP-DANDENONG',
      metadata: { lines: 2, totalCents: 222338, deliveryMethod: 'COLLECTION' },
      createdAt: new Date(now - 30 * 60 * 1000),
    },
    {
      action: 'ORDER_SUBMIT',
      userId: 'imranayla73@gmail.com',
      orderNumber: 'ORD-20260925-B202',
      tradeAccountId: 'ACC-001',
      rooftopId: 'ROOFTOP-DANDENONG',
      metadata: { lines: 2, totalCents: 336160, deliveryMethod: 'DELIVERY' },
      createdAt: new Date(now - 2 * 3600 * 1000),
    },
    {
      action: 'PICK',
      userId: 'counter.controller@booran.com.au',
      orderNumber: 'ORD-20260925-B202',
      rooftopId: 'ROOFTOP-DANDENONG',
      metadata: { lineId: 'LIN-02', partNumber: '43512-02250', binLocation: 'C-08' },
      createdAt: new Date(now - 15 * 60 * 1000),
    },
    {
      action: 'EXCEPTION',
      userId: 'counter.controller@booran.com.au',
      orderNumber: 'ORD-20260925-E505',
      tradeAccountId: 'ACC-000123',
      rooftopId: 'ROOFTOP-DANDENONG',
      metadata: { lineId: 'LIN-01', reason: 'OUT_OF_STOCK', action: 'RE_SOURCE_SISTER' },
      createdAt: new Date(now - 55 * 60 * 1000),
    },
    {
      action: 'PARTSCHECK_QUOTE_BACK',
      userId: 'SYSTEM_AUTONOMOUS',
      orderNumber: null,
      tradeAccountId: 'ACC-001',
      rooftopId: 'ROOFTOP-DANDENONG',
      metadata: { rfqId: 'PC-RFQ-10294', totalCents: 33520, slaMet: true },
      createdAt: new Date(now - 12 * 60 * 1000),
    },
  ];

  await db.collection('auditevents').insertMany(sampleAuditEvents);
  console.log(`✅ Inserted ${sampleAuditEvents.length} audit log events for the Activity Log feed.`);

  console.log('\n🚀 Mock Data Seeding Complete! All collections populated.');
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seeding failed:', err);
  process.exit(1);
});
