export enum LineExceptionReason {
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DAMAGED = 'DAMAGED',
  INCORRECT_BIN = 'INCORRECT_BIN',
  PRICING_DISCREPANCY = 'PRICING_DISCREPANCY',
  SUPERSEDED = 'SUPERSEDED',
  OTHER = 'OTHER',
}
