export enum OrderState {
  SUBMITTED = 'SUBMITTED',
  PROCESSING = 'PROCESSING',
  PARTIALLY_PICKED = 'PARTIALLY_PICKED',
  PICKED = 'PICKED',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  EXCEPTION = 'EXCEPTION',
  CANCELLED = 'CANCELLED',
}
