export enum RfqStatus {
  RECEIVED = 'RECEIVED',
  RESOLVING = 'RESOLVING',
  AUTO_QUOTED = 'AUTO_QUOTED',
  MANUALLY_QUOTED = 'MANUALLY_QUOTED',
  UNMAPPED_BUYER = 'UNMAPPED_BUYER',
  PENDING_REVIEW = 'PENDING_REVIEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum RfqLineStatus {
  PENDING = 'PENDING',
  RESOLVED = 'RESOLVED',
  OVERRIDDEN = 'OVERRIDDEN',
  UNAVAILABLE = 'UNAVAILABLE',
}
